from pathlib import Path

import requests
from .ngram_model import load_model, SmartNGramModel


OLLAMA_MODEL = "gemma3:4b"


def call_ollama(prompt: str, model: str = OLLAMA_MODEL, timeout: int = 120) -> str:
    url = "http://localhost:11434/api/generate"
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
    }

    try:
        resp = requests.post(url, json=payload, timeout=timeout)
    except requests.exceptions.ConnectionError:
        return "[ERROR] Cannot connect to Ollama at http://localhost:11434. Is it running?"
    except requests.exceptions.Timeout:
        return "[ERROR] Ollama request timed out."

    if resp.status_code != 200:
        return f"[ERROR] Ollama HTTP {resp.status_code}: {resp.text}"

    data = resp.json()

    return data.get("response", "").strip()


def build_prompt(user_input: str, draft: str, genre: str | None = None) -> str:
    genre_part = f"Genre: {genre}.\n" if genre else ""

    prompt = f"""
You are a story continuation assistant.

{genre_part}Your task is to continue the story in natural, fluent English.

Previous story fragment:
\"\"\"{user_input}\"\"\"

Rough continuation draft generated by a statistical n-gram model:
\"\"\"{draft}\"\"\"

Instructions:
- Use the rough draft only as inspiration for style and ideas, you may rewrite it.
- Produce a coherent continuation of the story in 2–4 sentences.
- Do not drastically change the setting introduced by the n-gram draft.
- Keep the same point of view, tense and general tone as the original fragment.
- Do not explain what you are doing, just output the continuation text only.
"""
    return prompt.strip()


def main():
    model_path = Path("models/ngram_4_smart.pkl")
    ngram: SmartNGramModel = load_model(model_path)
    print(f"Loaded smart n-gram model from {model_path}")

    while True:
        user_input = input("\nEnter story beginning (or 'quit'): ").strip()
        if not user_input or user_input.lower() in {"quit", "exit"}:
            break

        genre = input("Optional genre (e.g. 'horror', 'fantasy', 'comedy'; press Enter to skip): ").strip()
        if not genre:
            genre = None

        draft = ngram.generate_multi(user_input, num_sentences=3, max_tokens=80)
        print("\n[Smart n-gram draft]:")
        print(draft)

        prompt = build_prompt(user_input=user_input, draft=draft, genre=genre)

        print("\n[Calling LLM via Ollama...]\n")
        llm_output = call_ollama(prompt)

        print("[LLM continuation]:")
        print(llm_output)
        print("\n" + "-" * 60)


if __name__ == "__main__":
    main()
